service:
  port:
    name: http
    l4_protocol: TCP
    port: 80
    targetPort: 80
  label: frontend-service-1-uc7n1e4161
  name: frontend-service-1-uc7n1e4161
  selector: frontend-service-1-uc7n1e4161
  type:
  - ClusterIP
  - NodePort
namespace: demo-dev
pvc:
  name: pvc-frontend-service-1-uc7n1e4161
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: frontend-service-1-uc7n1e4161
    type: react
  replicas: 1
  update:
    type: RollingUpdate
  repo:
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
  image:
    name: frontend-service-1-uc7n1e4161
    tag: lastest
    secret: regsecret
  container:
    name: frontend-service-1-uc7n1e4161
    port: 80
  volume:
    name: pvc-frontend-service-1-uc7n1e4161
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  backing: 
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-frontend-service-1-uc7n1e4161
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
